ARG INVENTREE_VERSION=1.5.5
FROM inventree/inventree:${INVENTREE_VERSION}

COPY . /tmp/inventree-bambu-open
RUN pip install --no-cache-dir /tmp/inventree-bambu-open \
    && rm -rf /tmp/inventree-bambu-open
